// Bakes each skills/* directory whole into src/skills.generated.ts so the Worker
// can serve them — Workers have no filesystem at runtime. SKILL.md becomes the
// entry content; every other file in the directory is baked into a files map,
// fetchable via orchestra_get_skill's `file` argument (ADR-001: skills are
// served whole, never flattened). Run via `pnpm build:skills`.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const skillsDir = join(root, 'skills');
const outFile = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'skills.generated.ts');

function collectFiles(skillDir, base) {
  const files = {};
  for (const entry of readdirSync(skillDir, { withFileTypes: true })) {
    const full = join(skillDir, entry.name);
    if (entry.isDirectory()) {
      Object.assign(files, collectFiles(full, base));
    } else if (entry.isFile() && relative(base, full) !== 'SKILL.md') {
      files[relative(base, full)] = readFileSync(full, 'utf8');
    }
  }
  return files;
}

function parseSkill(raw, dir) {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!match) throw new Error(`${dir}/SKILL.md has no frontmatter`);

  const frontmatter = {};
  for (const line of match[1].split('\n')) {
    const kv = line.match(/^([A-Za-z_-]+):\s*(.*)$/);
    if (!kv) continue;
    let value = kv[2].trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
    frontmatter[kv[1]] = value;
  }

  const name = frontmatter.name;
  if (name !== dir) throw new Error(`${dir}/SKILL.md frontmatter name "${name}" does not match directory`);

  return {
    name,
    description: frontmatter.description ?? '',
    whenToUse: frontmatter.when_to_use ?? '',
    content: raw.slice(match[0].length).trim(),
  };
}

const skills = readdirSync(skillsDir, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => {
    const dir = join(skillsDir, e.name);
    return {
      ...parseSkill(readFileSync(join(dir, 'SKILL.md'), 'utf8'), e.name),
      files: collectFiles(dir, dir),
    };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

const banner = `// AUTO-GENERATED by scripts/build-skills.mjs — do not edit by hand.
// Source of truth: the skills/* directories at the repo root, served whole (ADR-001).

export interface SkillEntry {
  name: string;
  description: string;
  whenToUse: string;
  content: string;
  /** Support files (relative path → content), SKILL.md excluded. */
  files: Record<string, string>;
}
`;

const entries = skills
  .map((s) => `  ${JSON.stringify(s.name)}: ${JSON.stringify(s, null, 2).replace(/\n/g, '\n  ')},`)
  .join('\n');

writeFileSync(outFile, `${banner}
export const SKILLS: Record<string, SkillEntry> = {
${entries}
};

export const SKILL_NAMES = Object.keys(SKILLS);
`);

console.log(`wrote ${skills.length} skills to ${outFile}`);
